# Generated by Django 4.2.9 on 2026-02-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('appointments', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If true, only doctor can see this'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation'),
        ),
    ]
