# Generated by Django 4.2.9 on 2026-02-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='appointments/attachments/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('VIDEO', 'Video Consultation'), ('CLINIC', 'Clinic Visit')], default='CLINIC', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='urgency_level',
            field=models.CharField(choices=[('ROUTINE', 'Routine Checkup'), ('URGENT', 'Urgent Attention'), ('EMERGENCY', 'Emergency (Immediate)')], default='ROUTINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
