# Generated by Django 4.2.9 on 2026-02-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_attachment_appointment_consultation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('VIDEO', 'Video Consultation'), ('AUDIO', 'Audio Consultation'), ('CLINIC', 'Clinic Visit')], default='CLINIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for consultation', null=True),
        ),
    ]
